### ISSUE TITLE
编辑文档时会反复弹出通知

### ISSUE THREAD

**Issue by TCOTC** [Zuoqiu-Yingyi/siyuan-plugin-wakatime#24]
排查了半天，发现只要关闭这个插件就不会再弹通知了

在编辑数据库多选列时尤其频繁：

![插件](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-wakatime/assets/78434827/da66d50d-a5fe-4af3-87b3-013e537700e8)

**Comment by Zuoqiu-Yingyi** [comment]
是在思源 `v3.0.6` 版本中才出现的问题吗?

**Comment by TCOTC** [comment]
大概是（不过最近一直在用dev版，感觉一直有这个问题，所以不太确定）

**Comment by TCOTC** [comment]
关联：https://github.com/siyuan-note/siyuan/issues/10838
