### ISSUE TITLE
配置界面顶部的页签没有对齐

### ISSUE THREAD

**Issue by 88250** [Zuoqiu-Yingyi/siyuan-plugin-wakatime#27]
发现一个小问题，有空的话稍微调整一下，谢谢。

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-wakatime/assets/873584/4c1a6d55-23b9-4777-bdef-bb12b4613aaf)

**Comment by Zuoqiu-Yingyi** [comment]
最新版本 `0.3.6` 应该修复了该问题

**Comment by 88250** [comment]
确实修复了：

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-wakatime/assets/873584/160f3057-3bba-46a7-a5e6-51738b027a40)

点赞！
